<a href="https://colab.research.google.com/github/soo423/MachineLearning/blob/main/Chapter01_03_%EB%84%98%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1장 - 03. 넘파이(numpy)
import numpy as np로 사용하는 수치 연산의 핵심 라이브러리

In [ ]:
import numpy as np

#npdaary 생성
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array형태 : ', array1.shape) #1차원

#2행 3열의 2차원 배열
array2 = np.array([[1,2,3],[2,3,4]])
print('array2 type:', type(array2))
print('array2 array형태 : ', array2.shape)

#1행 3열의 2차원 배열
array3 = np.array([[1, 2, 3]])
print('array3 type :', type(array3))
print('array3 array형태 : ', array3.shape)

array1 type: <class 'numpy.ndarray'>
array1 array형태 :  (3,)
array2 type: <class 'numpy.ndarray'>
array2 array형태 :  (2, 3)
array3 type : <class 'numpy.ndarray'>
array3 array형태 :  (1, 3)


In [ ]:
#ndim : 배열의 차원 수 확인
#shape가 (3,)이면 1차원, (1,3)이면 2차원
#[1,2,3]과 [[1,2,3]]은 차원이 다름
print(f'{array1.ndim}차원, {array3.ndim}차원')

1차원, 2차원


In [ ]:
list1 = [1, 2, 4]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 4] int64


In [ ]:
#데이터 타입 자동 변환 규칙, ndarray는 단일 타입만 허용, 더 큰 타입으로 자동 변환
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [ ]:
#astype() : 명시적 타입 변환
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype) #소수점 버림

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [ ]:
#np.arange(): 연속 정수 배열 생성
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [ ]:
## ---- np.zeros() : 모든 원소가 0인 배열
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [ ]:
#np.ones() : 모든 원소가 1인 배열
one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [ ]:
#reshape() : 원소 수는 그대로, 형태만 변경
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2, 5)
print('array2:\n', array2)

array3 = array1.reshape(5, 2)
print('array3:\n', array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#reshape() 오류 : 원소 수가 맞지 않으면 ValueError
try:
  array1.reshape(4, 3)
except ValueError as e:
  print('오류 발생:', e)

오류 발생: cannot reshape array of size 10 into shape (4,3)


In [ ]:
# -1인수 : 나머지 차원 자동 계산
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(-1, 5) #열=5, 행= 원소10/5=2 -> (2,5)
print('array2 shape:', array2.shape)

array3 = array1.reshape(5, -1) #행=5, 열= 원소10/5=2 ->(5,2)
print('array3 shape:', array3.shape)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [ ]:
# -1 인수 오류 : 균등하게 나눠지지 않으면 ValueError
try:
  array4 = array1.reshape(-1, 4)
except ValueError as e:
  print('오류 발생:', e)

오류 발생: cannot reshape array of size 10 into shape (4)


In [ ]:
# reshape(-1, 1): 머신러닝에서 가장 많이 쓰는 패턴
#머신러닝 라이브러리 사이킷런(scikit-learn)은 2D 배열 입력을 요구

array1 = np.arange(8)
print('array1\n', array1)
array3d = array1.reshape((2,2,2)) #3차원 배열 생성
print('array3d:\n', array3d.tolist())

#3차원 -> 2차원(열벡터 column vector)
array5 = array3d.reshape(-1, 1) #-1: 자동 계산을 의미, 1: 열의 개수를 1로 지정
print('array5"\n', array5.tolist())
print('array5 shape:', array5.shape) #원소 갯수만큼 행 수 생성

#1차원 -> 2차원(열벡터)
array6 = array1.reshape(-1, 1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array1
 [0 1 2 3 4 5 6 7]
array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5"
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [ ]:
#인덱싱(indexing)
#1차원 배열 단일값 추출
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
print('value:', value)
print(type(value))

#음수 인덱스 : 뒤에서부터 계산
print('맨 뒤의 값:', array1[-1], ', 맨 뒤에서 두번째 값:', array1[-2])

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>
맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [ ]:
#2차원 배열 단일값 추출: array[행, 열]
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)
print(f'array2d[0,0]:{array2d[0, 0]}')
print(f'array2d[0,1]:{array2d[0, 1]}')
print(f'array2d[1,0]:{array2d[1, 0]}')
print(f'array2d[2,2]:{array2d[2, 2]}')

In [ ]:
#슬라이싱(Slicing)
#1차원 슬라이싱
array1 = np.arange(start=1, stop=10)
print(array1)

array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3 4 5 6 7 8 9]
[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
#슬라이싱 축약 표현
array4 = array1[:3] #처음~index 2
print(array4)


array5 = array1[3:] #index 3 ~ 끝
print(array5)

array6 = array1[:] #전체
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#2차원 슬라이싱 : array[행 범위: , 열 범위:]
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print(f'array2d[0:2, 0:2] \n= {array2d[0:2, 0:2]}')
print(f'array2d[1:3, 0:3] \n= {array2d[1:3, 0:3]}')
print(f'array2d[1:3, :] \n= {array2d[1:3, :]}')
print(f'array2d[:, :] \n={array2d[:, :]}')
print(f'array2d[:2, 1:] \n={array2d[:2, 1:]}')
print(f'array2d[:2, 0] \n={array2d[:2, 0]}') #결과 1차원

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
= [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
= [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
= [[4 5 6]
 [7 8 9]]
array2d[:, :] 
=[[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
=[[2 3]
 [5 6]]
array2d[:2, 0] 
=[1 4]


In [ ]:
#행 인덱스만 지정하면 해당 행 전체를 1차원으로 반환
print(array2d[0], array2d[0].shape) #array[0, :]
print(array2d[1], array2d[1].shape) #array[1, :]

[1 2 3] (3,)
[4 5 6] (3,)


In [ ]:
#팬시 인덱싱(fancy indexing)
#팬시 인덱싱 : 리스트로 여러 위치 동시 선택
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n', array2d)

print(f'array2d([0, 1], 2) \n= {array2d[[0, 1], 2]}')
print(f'array2d[[0, 1], 0:2] \n= {array2d[[0, 1], 0:2]}')
print(f'array2d[[0, 1]] \n= {array2d[[0, 1]]}') #[0, 1]번행 전체

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d([0, 1], 2) 
= [3 6]
array2d[[0, 1], 0:2] 
= [[1 2]
 [4 5]]
array2d[[0, 1]] 
= [[1 2 3]
 [4 5 6]]


In [ ]:
#불린 인덱싱(boolean indexing)
array1d = np.arange(start=1, stop=10)
print(array1d)
array3 = array1d[array1d > 5]
print(array3)

print(array1d > 5)
boolean_indexes = np.array([False, False, False, False, False, True, True, True, True])
print(boolean_indexes)
array3 = array1d[boolean_indexes]
print(array3)

#일반 정수 인덱스와 비교
indexes = np.array([5, 6, 7, 8])
print(indexes)
array4 = array1d[indexes]
print(array4)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]
[False False False False False  True  True  True  True]
[6 7 8 9]


In [ ]:
#행렬의 정렬 - sort()와 argsort()
# np.sort() : 정렬된 새 배열 반환, 원본 변경 없음
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)

sort_array1 = np.array([3, 1, 9, 5])
print(f'sort_array1 = {sort_array1}')
print(f'org_array = {org_array}')

# ndarray.sort() : 원본 직접 정렬, None 반환
sort_array2 = org_array.sort()
print(f'sort_array2 = {sort_array2}')
print(f'org_array = {org_array}')

원본 행렬: [3 1 9 5]
sort_array1 = [3 1 9 5]
org_array = [3 1 9 5]
sort_array2 = None
org_array = [1 3 5 9]


In [ ]:
#내림차순 정렬: [:: -1] 슬라이싱 활용
sort_array1_desc = np.sort(org_array)[::-1] #오름차순 정렬 후 역순
print('내림차순으로 정렬:',sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [ ]:
#2차원 배열 정렬 : axis 인수로 방향 지정
array2d = np.array([[8, 12], [7, 1]])
sort_array2d_axis0 = np.sort(array2d, axis=0) #axis=0 행, 각 열 내에서 행끼리 비교
print('행 방향으로 정렬 : \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1) #axis=1 열, 각 행 내에서 열끼리 비교
print('열 방향으로 정렬 : \n', sort_array2d_axis1)

행 방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
열 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


In [ ]:
#정렬 행렬의 인덱스 반환 - argsort()
#argsort() : 정렬 후 원래 인덱스를 반환
org_array = np.array([3, 1, 9, 5]) #오름차순 정렬 시 [1, 3, 5, 9]
sort_indices = np.argsort(org_array)
print('행렬 정렬 시 원본 행렬의 인덱스',sort_indices)

행렬 정렬 시 원본 행렬의 인덱스 [1 0 3 2]


In [ ]:
#내림차순 argsort : [::-1] 적용
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1] #내림차순 정렬 시 [9, 5, 3, 1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [ ]:
#두 배열이 같은 인덱스로 연결되어 있을 때 argsort로 함께 정렬
#점수 기준으로 이름 정렬
name_array = np.array(['김', '이', '정', '박', '최'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_desc = np.argsort(score_array) #78, 84, 88, 95, 88
print('성적 오름차순 정렬 시 score_array의 인덱스', sort_indices_desc)

#같은 인덱스로 name_array도 정렬
print('성적 오름차순:', score_array[sort_indices_desc])
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_desc])

성적 오름차순 정렬 시 score_array의 인덱스 [0 2 4 1 3]
성적 오름차순: [78 84 88 95 98]
성적 오름차순으로 name_array의 이름 출력: ['김' '정' '최' '이' '박']


In [ ]:
#선형대수 연산
#행렬 내적 - np.dot(A, B)
A = np.array([[1, 2, 3], [4, 5, 6]]) #shape(2, 3)
B = np.array([[7, 8],[9, 10],[11, 12]]) #shape(3, 2)

dot_product = np.dot(A, B) #(2, 3) X (3, 2) -> (2, 2)
print('행렬 내적 결과 : \n', dot_product)
# [[ 58  64] 1*7+2*9+3*11=58 1*8+2*10+3*12=64
# [139 154]] 4*7+5*9+6*11=139......

행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


In [ ]:
#전치 행렬 - np.transpose() 행과 열을 바꿈
#A[i][j] -> A,T[j][i]
A = np.array([[1, 2],[3, 4]]) #shape(2, 2)
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
